meta_product_name: "Dionysos"
meta_title: "Dionysos - L'événementiel simple"
meta_description: "Avec Dionysos, rassemblez toutes les fonctionnalités nécessaires à l’organisation de votre événement dans une seule interface !"
meta_image: "https://res.cloudinary.com/dct6y4tya/image/upload/v1670493272/pexels-photo-634694_vhq5nj.jpg" # should exist in `app/assets/images/`
